### PR TITLE
Added license and readme

### PR DESCRIPTION
**Pull request by Puthranps**

### CODE REVIEW

**Comment by exrook** [comment]
Please add more information to the readme

**Comment by Puthranps** [comment]
@exrook what information would you like

**Comment by exrook** [comment]
This description is inadequate and does not inspire faith in the project. Please produce 2-3 well written sentences describing the project and place them in the readme

**Comment by Puthranps** [comment]
@exrook as you wish

**Comment by Chris-Perkins** [comment]
Approved

**Comment by exrook** [comment]
LGTM 👍

**Pull request merged**
